name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install deps
        run: |
          python -m pip install -U pip
          python -m pip install -U build setuptools wheel twine
      - name: extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: build
        env:
          RELEASE_VERSION: ${{ steps.extract_branch.outputs.branch }}
        run: |
          python -m build
      - name: check
        run: |
          python -m twine check dist/*
      - name: upload
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_API_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
