name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [
        {version: "3.8", pyxx: py38},
        {version: "3.9", pyxx: py39},
        {version: "3.10", pyxx: py310},
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.version }}
      - name: install deps
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.python.pyxx }}
